version: '3.1'

services:
  database-crud:
    container_name: dsw-crud-database
    image: mongo
    restart: always
    command: mongod --port 27027
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cruddb
    ports:
      - "27027:27027"
    volumes:
      - "./database-scripts:/database-scripts"

  dsw-crud:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dsw-crud-api
    ports:
      - "4040:4040"
    volumes:
      - ./backend:/home/node/app
    tty: true
    depends_on:
      - database-crud

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dsw-crud-front
    ports:
      - "5050:80"
    links:
      - dsw-crud