version: '3.1'

services:
  database: 
    container_name: databaseMongo
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: crudDB
    ports:
      - "27017:27017"
    volumes:
      - "./database-scripts:/database-scripts"