# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: develop

jobs:
  test:
    name: test and lint 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 12.*

    - name: build test frontend
      run: |
        cd frontend/
        npm install
        npm run build
        
    - name: build test backend
      run: |
        cd backend/
        npm install
        npm run format
        npm run build 
