name: CI/test

# Controls when the workflow will run
on:
  pull_request:
    branches: develop

jobs:
  test:
    name: test and lint 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 12.*
    - name: build and test backend
      run: |
        npm install
        npm run build
        npm run test
